title = "Adventure In Tandem"
baseURL = "https://romantic-jennings-33dba8.netlify.com"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-97691549-3"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "black-tandem.ico"
  description = "Tandem adventures around the world."
  facebook = "https://facebook.com/adventureintandem"
  twitter = ""
  instagram = "https://instagram.com/adventure.in.tandem/"
  youtube = "https://youtube.com/channel/UCNbxhfONYLb4JZW0aNNSC4g"
  github = ""
  gitlab = ""
  linkedin = ""
  strava = "https://www.strava.com/athletes/7594"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/images/tandem.jpg"
  recent_posts_number = 8
  cover_dimming_class = ""

[permalinks]
  blog = "/:slug/"
